#!/usr/bin/env python

import sys
import netaddr


def main(argv):
    file_name = argv[0]

    fh_host = open("github_host.txt")
    github_host = fh_host.read()
    fh_host.close()

    fh_host = open("bitbucket_host.txt")
    bitbucket_host = fh_host.read()
    fh_host.close()

    print "modifying: " + file_name
    fh = open(file_name, "w+")
    # github = netaddr.IPNetwork('192.0.4.0/25')
    github = netaddr.IPNetwork('192.30.252.0/22')
    # for ip in github:
    ips = list(github)
    # print ips[0], ips[1023]

    for ip in ips:
        fh.write(github_host.format(ip=ip))

    fh.write(bitbucket_host.format(ip="207.223.240.181"))
    fh.write(bitbucket_host.format(ip="207.223.240.182"))
    fh.write(bitbucket_host.format(ip="131.103.20.167"))
    fh.write(bitbucket_host.format(ip="131.103.20.168"))
    fh.write(bitbucket_host.format(ip="131.103.20.169"))
    fh.write(bitbucket_host.format(ip="131.103.20.170"))

    print "{0} ips for github added".format(len(ips))
    print "{0} ips for bitbucket added".format(6)

    fh.close()
    # print github.hosts()


if __name__ == "__main__":
    main(sys.argv[1:])
